name: Deploy

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUD_UNAME: ${{ secrets.CLOUD_UNAME }}
      CLOUD_HOST: ${{ secrets.CLOUD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Preparation
        run: |
          sudo apt-get update
          sudo apt-get install rsync -y
          mkdir "$HOME/.ssh"
          echo "${{ secrets.CLOUD_PRIVATE_KEY }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
      - name: Sync
        run: |
          rsync -e "ssh -p 23348 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" -avz --exclude '.git' --chown=github:www-data --chmod=Dg=rwx,Fg=rwx --archive --compress --delete . $CLOUD_HOST@$CLOUD_UNAME:/home/$CLOUD_UNAME/deploy
      - name: Build
        run: |
          ssh -p 23348 -i $HOME/.ssh/key $CLOUD_HOST@$CLOUD_UNAME 'cd /home/alexey/labs/K33392/Korotin_Alexey/lab2 && docker compose up -d --build'
